name = "Lakshin's Portfolio"
license = "MIT"
licenselink = "https://github.com/Lakshin01/portfolio/blob/master/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/Lakshin01/portfolio"
demosite = "https://lakshin.netlify.app"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "Lakshin Kumar"
  homepage = "https://www.linkedin.com/in/lakshin-kumar"
